[General]
csfFile = general.csf
discordUrl=https://discord.gg/yxkVn4wBad

serversUrl=//gateway.chronodivide.com/legacy/realms/servers.ini

gameResArchiveUrl=https://archive.org/download/red-alert-2-multiplayer/Red-Alert-2-Multiplayer.exe
gameResExpansionArchiveUrl=https://archive.org/download/yuris-revenge-multiplayer/Yuris-Revenge-Multiplayer.exe
gameResExpansionMusicUrl=https://xwis.net/dl/thememd.mix

gameresBaseUrl=/cdn/game-res/v2/
mapsBaseUrl=/cdn/maps/
modsBaseUrl=/cdn/mods/
; mapsBaseUrl=//gameres.chronodivide.com/map/
; modsBaseUrl=//gameres.chronodivide.com/mod/
patchNotesUrl=//chronodivide.com/patch-notes.html
ladderRulesUrl=//chronodivide.com/ladder-rules.html
modSdkUrl=https://github.com/chronodivide/mod-sdk
donateUrl="//chronodivide.com/#donate"
replaysUrlWhitelist=".chronodivide.com"
breakingNewsUrl=/breaking-news.html
; breakingNewsUrl=//gameres.chronodivide.com/content/breaking-news.html
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
checkMixesIntegrity=false
unrankedQueueEnabled=yes
botsEnabled=yes
debugLogging=wol
debugGameState=yes
defaultLanguage=en-US
viewport.width=1024
viewport.height=768

[Gateway]
baseUrl=//gateway.chronodivide.com/

[AuthProvider.discord]
enabled=yes

[CorsProxy]
archive.org="https://game.chronodivide.com/cors-proxy/?url="
xwis.net="https://game.chronodivide.com/cors-proxy/?url="

[Sentry]
dsn=https://6930de63a43742fbab115ee9b8d39891@o1333351.ingest.us.sentry.io/6598680
tunnel=/dbgdump
env=prod
defaultIntegrations=yes
autoSessionTracking=no