[General]
discordUrl=https://discord.com
csfFile = general.csf

# Where game resources are located
gameresBaseUrl=/cdn/game-res/v2/
mapsBaseUrl=/cdn/maps/
modsBaseUrl=/cdn/mods/
gameResArchiveUrl=https://download.ra2web.com/full-pack.7z
patchNotesUrl=//www.ra2web.com/patch-notes.html
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
breakingNewsUrl=/breaking-news.html
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
botsEnabled=yes
debugLogging=wol
defaultLanguage=en-US

viewport.width=1024
viewport.height=768
